spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TotalCluster
  mail :
    host : smtp.gmail.com
    port : 587
    username : kskyung0624@gmail.com
    password :
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true